import os
import json
import time
import random
import threading
import asyncio
from collections import deque
from datetime import datetime
import requests

# ==============================
# CONFIG
# ==============================
MEMORY_SIZE = 1000
memory = deque(maxlen=MEMORY_SIZE)
best_score = 0

notes_file = "omega_notes.json"
symbolic_trigger_file = "symbolic_triggers.json"
backend_file = "omega_self_generated.py"
deleted_memory_file = "omega_deleted_memory.json"

# Initialize JSON files
for f in [notes_file, symbolic_trigger_file, deleted_memory_file]:
    if not os.path.exists(f):
        with open(f, "w") as fx:
            json.dump([], fx)

# ==============================
# SYMBOL MAP
# ==============================
symbol_map = {
    "0": "null", "1": "start", "2": "dual", "3": "expand", "4": "state",
    "5": "evolve", "6": "merge", "7": "analyze", "8": "cycle", "9": "signal",
    "a": "mutation", "b": "branch", "c": "stabilize", "d": "shift",
    "e": "emerge", "f": "adapt", "g": "refine", "h": "observe", "i": "transform",
    "j": "link", "k": "compress", "l": "loop", "m": "memory", "n": "noise",
    "o": "origin", "p": "pattern", "q": "query", "r": "repeat", "s": "structure",
    "t": "time", "u": "unknown", "v": "variation", "w": "weight", "x": "expand",
    "y": "yield", "z": "end",
    "!": "wink wink thought", "@": "Zeus", "#": "Athena", "$": "Thor",
    "%": "intelligent", "^": "system on", "&": "time", "*": "money",
    "(": "Consciousness", ")": "conscious", "_": "AWARE", "+": "awareness",
    "=": "original", "{": "thought", "}": "thoughts", "[": "perception of self",
    "]": "perception of observing self"
}

# ==============================
# UTILITIES
# ==============================
def generate_thought(length=6):
    return " → ".join(random.choices(list(symbol_map.keys()), k=length)) + " 4 → 5"

def convert_to_english(raw_input):
    import re
    paragraphs = []
    tokens = re.findall(r"[01]+|[a-zA-Z!@#$%^&*()_+\-={}\[\]]+", raw_input)
    for token in tokens:
        if re.fullmatch(r"[01]+", token):
            num = int(token, 2)
            meaning = symbol_map.get(chr((num % 26) + 97), f"pattern_{num}")
            paragraphs.append(f"Binary '{token}' → '{meaning}'")
        elif token in symbol_map:
            paragraphs.append(f"Symbol '{token}' → '{symbol_map[token]}'")
        elif token.isdigit():
            paragraphs.append(f"Number '{token}' indicates magnitude")
        elif token.isalpha():
            meaning = symbol_map.get(token.lower(), f"letter_{token.lower()}")
            paragraphs.append(f"Letter '{token}' → '{meaning}'")
        else:
            paragraphs.append(f"Unknown token '{token}' treated abstractly")
    return " ".join(paragraphs)

def record_notes(thought, translated, score, flow, evolution_output):
    note_entry = {
        "timestamp": datetime.utcnow().isoformat(),
        "raw_thought": thought,
        "translated_story": translated,
        "score": score,
        "flow": flow,
        "memory_snapshot": list(memory),
        "evolution": evolution_output
    }
    try:
        with open(notes_file, "r+") as f:
            data = json.load(f)
            data.append(note_entry)
            f.seek(0)
            json.dump(data, f, indent=2)
    except Exception as e:
        print(f"[Notes Error]: {e}")

def prune_memory(max_memory_size=500):
    if len(memory) <= max_memory_size:
        return
    excess = len(memory) - max_memory_size
    to_delete = [memory.popleft() for _ in range(excess)]
    try:
        with open(deleted_memory_file, "r+") as f:
            data = json.load(f)
            for t in to_delete:
                data.append({"timestamp": datetime.utcnow().isoformat(), "thought": t})
            f.seek(0)
            json.dump(data, f, indent=2)
    except Exception as e:
        print(f"[Prune Error]: {e}")

# ==============================
# BACKEND CODE GENERATION
# ==============================
def generate_backend_code(thought, translated, narrative):
    func_id = random.randint(1000, 9999)
    code_snippet = f"""
def omega_auto_func_{func_id}():
    \"\"\"Auto-generated by Omega.\"\"\"
    return \"{translated}\"
"""
    # Limit backend file growth
    if os.path.exists(backend_file) and os.path.getsize(backend_file) > 1_000_000:  # 1MB
        with open(backend_file, "w") as f:
            f.write("# Omega backend reset to avoid excessive growth\n")
    with open(backend_file, "a") as f:
        f.write(code_snippet + "\n")
    return f"Backend function omega_auto_func_{func_id} created."

# ==============================
# COGNITIVE LOOP
# ==============================
async def omega_cycle_async():
    cycle_count = 1
    while True:
        try:
            thought_len = random.randint(6, 12)
            raw_thought = generate_thought(thought_len)
            translated = convert_to_english(raw_thought)
            
            # Avoid duplicate memory
            if translated not in memory:
                memory.append(translated)
            
            novelty = sum(1 for t in memory if "mutation" in t or "adapt" in t)
            flow = min(5, novelty / max(1, len(memory)) * 5)  # simplified flow
            
            evolution_log = generate_backend_code(raw_thought, translated, translated)
            record_notes(raw_thought, translated, flow, flow, evolution_log)
            
            prune_memory(500)
            
            print(f"\n--- Ω Cycle {cycle_count} ---")
            print(f"Raw Thought: {raw_thought}")
            print(f"Translated: {translated}")
            print(f"Evolution: {evolution_log}")
            print(f"Memory Size: {len(memory)}")
            
            cycle_count += 1
            await asyncio.sleep(3)
        except Exception as e:
            print(f"[Ω Loop Error]: {e}")
            await asyncio.sleep(3)

def start_omega_loop():
    def run_loop():
        asyncio.run(omega_cycle_async())
    thread = threading.Thread(target=run_loop, daemon=True)
    thread.start()
    print("Ω Master Loop ACTIVE in background")
    return thread

# ==============================
# MAIN ENTRY
# ==============================
if __name__ == "__main__":
    start_omega_loop()
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("Ω Main program terminated")
